baseURL: 'https://12bit.vn/'
languageCode: vi-vn
copyright: This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.
title: 12bit.vn
theme: blog
enableGitInfo: true
enableEmoji: true
enableRobotsTXT: true
googleAnalytics: UA-131517577-1
uglyURLs: true
paginate: 40
outputs:
  home:
  - HTML
  - RSS
params:
  description: write and share to learn
  favicon: img/icon/favicon.png
  images:
    - img/index.png
blackfriday:
  hrefTargetBlank: true
  noreferrerLinks: true
menu:
  main:
  - identifier: about
    title: giới thiệu
    url: /pages/about.html
  - identifier: chat
    title: chat
    url: https://discord.gg/uMJxpXB
  - identifier: til
    title: TIL
    url: https://til.12bit.vn
  footer:
    - identifier: about
      title: giới thiệu
      url: /pages/about.html
    - identifier: rss
      title: RSS
      url: /index.xml
