languageCode: vi-vn
copyright: This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.
title: 12bit.vn
description: write and share to learn
baseURL: https://12bit.vn/
theme: blog
enableGitInfo: true
enableEmoji: true
enableRobotsTXT: true
googleAnalytics: UA-131517577-1
paginate: 40
social:
  facebook: 12bit.vn
author:
  email: contact@12bit.vn
  name: 12bit.vn
authors:
  vominh:
    displayName: Vô Minh
    social:
      website: https://12bit.vn
  tatthien:
    displayName: Thiện
    social:
      website: https://12bit.vn
outputs:
  home:
  - HTML
  - RSS
  - Algolia
params:
  description: write and share to learn
  favicon: img/icon/favicon.png
  images:
    - img/index.png
  mailChimpSubmitURL: 'https://12bit.us7.list-manage.com/subscribe/post?u=ed33685285a694c7d5b00b64b&amp;id=58d0a80dbd'
  facebookAppId: 363747664413304
  algolia:
    vars: ["title", "content", "summary", "date", "publishdate", "permalink"]
    params: ["tags"]

outputFormats:
  Algolia:
    baseName: algolia
    isPlainText: true
    mediaType: application/json
    notAlternative: true

blackfriday:
  hrefTargetBlank: true
  noreferrerLinks: true
  nofollowLinks: true
menu:
  main:
  - identifier: about
    title: Giới thiệu
    url: /pages/about.html
  - identifier: chat
    title: Chat
    url: https://discord.gg/uMJxpXB
  - identifier: News
    title: News
    url: https://news.12bit.vn
  footer:
    - identifier: 0
      title: Series
      url: /series/
    - identifier: 1
      title: References
      url: /references/
    - identifier: 2
      title: Donate
      url:  https://ko-fi.com/12bitvn
    - identifier: 3
      title: RSS
      url: /index.xml
taxonomies:
  series: series
  tag: tags
  reference-tag: reference-tags
#hooks:
  #onPageCreated: social-image-gen --output={abs_publish_dir} --title={title} --date={date} --author={author} --template=./social-image.html
