baseURL = "https://12bit-blog.netlify.com/"
languageCode = "vi-vn"
title = "12bit.vn"
theme = "blog"
enableGitInfo = true
disqusShortname = "shortname"
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = "UA-126210212-1"
uglyURLs=true
paginate=20

[outputs]
  home = ["HTML", "RSS"]

[params]
  description = "write and share to learn"
  favicon = "img/icon/favicon.png"

[blackfriday]
  hrefTargetBlank = true
