baseURL = "https://note.tatthien.com"
languageCode = "vi-vn"
title = "12bit.vn"
theme = "blog"
enableGitInfo = true
disqusShortname = "shortname"
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = "UA-126210212-1"
uglyURLs=true
paginate=20


[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "content", "summary", "date", "publishdate", "permalink"]
params = ["tags"]

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  description = "write and share to learn"
  favicon = "img/icon/favicon.png"
[blackfriday]
  hrefTargetBlank = true
