[build]
publish = "public"
command = "./bin/hugo"

[context.production.environment]
HUGO_VERSION = "0.48"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "./bin/hugo --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.48"
HUGO_ENV = "production"

[context.deploy-preview]
command = "./bin/hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.48"

[context.branch-deploy]
command = "./bin/hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.48"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
