# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Minitil"
license = "MIT"
licenselink = "https://github.com/12bit/minitil/blob/master/LICENSE"
description = "Minimal TIL theme for Hugo"
homepage = "http://example.com/"
tags = []
features = []
min_version = "0.41"

[author]
  name = "12bit"
  homepage = "https://12bit.vn"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
