on: [push]
name: Publish blog
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true
    - name: Build
      run: hugo --gc --minify --buildFuture --cleanDestinationDir
    - uses: actions/setup-node@master
    - name: Preacache
      run: yarn run precache
    - name: Algolia
      run: yarn run algolia
      env:
        ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
        ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
        ALGOLIA_INDEX_NAME: prod_12bit_blog
        ALGOLIA_INDEX_FILE: public/algolia.json
    - name: Deploy
      run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}" --only hosting:production
