name: Build project and Run Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.3.0
        with:
          extended: true
      - name: Build site for production
        run: |
          HUGO_ENV=production hugo  --gc --minify --buildFuture --cleanDestinationDir
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.3.x
          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
