on: [pull_request]
name: Preview
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      - name: Build
        run: hugo --gc --minify --buildFuture --cleanDestinationDir
      - uses: actions/setup-node@master
      - name: Install dependencies
        run: yarn install
      - name: Deploy preview
        run: yarn preview
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
