on: [pull_request]
name: Preview
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      - name: Build
        run: hugo --gc --minify --buildFuture --cleanDestinationDir
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@master
        with:
          version: 6.0.2
          run_install: true
      - name: Deploy preview
        run: pnpm preview
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
